import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  HomeOutline,
  SearchOutline,
  UpCircleTwoTone,
  FileOutline,
  ContactsOutline,
  AppstoreOutline,
  FileProtectOutline,
  BankOutline,
  ToolOutline,
  TeamOutline,
  ApartmentOutline,
  MessageOutline,
  FileTextOutline,
  FileDoneOutline,
  CreditCardOutline,
  StarOutline,
  DollarOutline,
  UserOutline,
  FileSearchOutline,
  SettingOutline,
  UserAddOutline,
  DownOutline,
  BellOutline,
  CheckOutline,
  NotificationOutline,
  EnvironmentOutline,
  PhoneOutline,
  MailOutline,
  FacebookOutline,
  YoutubeOutline,
  EditOutline,
  DeleteOutline,
  PlusCircleOutline,
  LogoutOutline,
  EyeOutline,
  CloseOutline,
  HistoryOutline,
  LockOutline,
} from '@ant-design/icons-angular/icons';

const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  HomeOutline,
  SearchOutline,
  UpCircleTwoTone,
  FileOutline,
  ContactsOutline,
  AppstoreOutline,
  FileProtectOutline,
  BankOutline,
  ToolOutline,
  TeamOutline,
  ApartmentOutline,
  MessageOutline,
  FileTextOutline,
  FileDoneOutline,
  CreditCardOutline,
  StarOutline,
  DollarOutline,
  UserOutline,
  FileSearchOutline,
  SettingOutline,
  UserAddOutline,
  DownOutline,
  BellOutline,
  CheckOutline,
  NotificationOutline,
  EnvironmentOutline,
  PhoneOutline,
  MailOutline,
  FacebookOutline,
  YoutubeOutline,
  EditOutline,
  DeleteOutline,
  PlusCircleOutline,
  LogoutOutline,
  EyeOutline,
  CloseOutline,
  HistoryOutline,
  LockOutline,
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {}
